repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.21.0
    hooks:
      - id: eslint
        args: [--fix]
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin@^4.31.1"
          - "@typescript-eslint/parser@^4.31.1"
          - "typescript@4.5.2"
          - "eslint@^7.32.0"
