openapi: 3.1.0
info:
  title: proxy-up
  version: 0.0.1

security:
  - AuthHeader: []

servers:
  - url: "https://up.vc.mause.me"

components:
  securitySchemes:
    AuthHeader:
      scheme: header
      type: http
paths:
  /api/up:
    get:
      operationId: getUp
      parameters:
        - in: query
          name: includeNegative
          schema:
            type: boolean
          required: false
        - in: query
          name: page[after]
          schema:
            type: string
          required: false
        - in: query
          name: page[size]
          schema:
              type: number
          required: false
