on: push

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          cache: yarn
      - run: yarn --frozen
      - name: TypeScript Error Reporter
        uses: gozala/typescript-error-reporter-action@v1.0.5
      - run: yarn build
      - run: yarn test
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: openapi.yaml
          path: public/openapi.yaml
