on: push
permissions:
  checks: write

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.2
        with:
          cache: yarn
      - run: yarn --frozen
      #       - name: TypeScript Error Reporter
      #         uses: spin-org/typescript-error-reporter-action@v1.0.11
      - run: yarn build
      - run: yarn test
      - uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: openapi.yaml
          path: public/openapi.yaml
