on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}

name: Update client
jobs:
  update_client:
    name: Update client
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: up
            url: https://github.com/up-banking/api/raw/master/v1/openapi.json

    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Update types
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            npx @openapitools/openapi-generator-cli generate -i ${{ matrix.url }}?apikey=${{ secrets.SUPABASE_KEY }} -o src/${{ matrix.name }} -g typescript-axios
            npx prettier . --write
          COMMIT_MESSAGE: "chore: update ${{ matrix.name }} client"
          COMMIT_NAME: "GitHub Actions"
          COMMIT_EMAIL: "example@example.com"
          PR_BRANCH_NAME: "chore-${{ matrix.name }}-update-client-${PR_ID}"
          PR_TITLE: "chore: update ${{ matrix.name }} client"
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
